// resources/js/components/pages/stock-locations/Update.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter, useRoute } from "vue-router";
import Content from "../../common/Content.vue";
import Card from "../../common/Card.vue";
import { useStockLocationStore } from "../../../stores/stock-location";
import StockLocationForm from "../../common/StockLocationForm.vue";

const store = useStockLocationStore();

const router = useRouter();
const route = useRoute();

// Load location data for editing
store.loadStockLocation(parseInt(route.params.id as string));

// Handle form submission
const submitForm = async () => {
    const success = await store.updateStockLocationItem();
    if (!success) return;
    // Redirect to stock location detail page on success
    router.push(`/stock-locations/${store?.stockLocation?.id}`);
};
</script>

<template>
    <Content>
        <Card>
            <template #title>Edit Stock Location</template>

            <StockLocationForm @submit-form="submitForm" />
        </Card>
    </Content>
</template>

// resources/js/pages/stock-locations/update.component.ts
import { Component, OnInit, inject } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { CardComponent } from '../../components/common/card.component'
import { ContentComponent } from '../../components/common/content.component'
import { StockLocationFormComponent } from '../../components/common/stock-location-form.component'
import { StockLocationService } from '../../services/stock-location.service'

@Component({
  selector: 'app-stock-locations-update',
  standalone: true,
  imports: [CommonModule, CardComponent, ContentComponent, StockLocationFormComponent],
  template: `
    <app-content>
      <app-card>
        <span slot="title">Edit Stock Location</span>
        <app-stock-location-form (submitForm)="submitForm()" />
      </app-card>
    </app-content>
  `,
})
export class StockLocationUpdateComponent implements OnInit {
  private stockLocationService = inject(StockLocationService)
  private router = inject(Router)
  private route = inject(ActivatedRoute)

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id')
    if (id) {
      this.stockLocationService.loadStockLocation(parseInt(id))
    }
  }

  async submitForm(): Promise<void> {
    const success = await this.stockLocationService.updateStockLocation()
    if (!success) return
    await this.router.navigate(['/stock-locations', this.stockLocationService.stockLocation()!.id])
  }
}
