// resources/js/components/App.vue
<script setup>
import { useAuthStore } from "../stores/auth";
import NavMain from "./nav/NavMain.vue";
import NavGuest from "./nav/NavGuest.vue";

const authStore = useAuthStore();
authStore.setUser(window?.App?.user || null);
</script>

<template>
    <div id="app">
        <nav-main v-if="authStore.isAuthenticated" />
        <nav-guest v-else />
        <main class="py-6 bg-white dark:bg-gray-900">
            <router-view />
        </main>
    </div>
</template>

// resources/js/app.component.ts
import { Component, OnInit, inject } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterOutlet } from '@angular/router'
import { AuthService } from './services/auth.service'
import { NavMainComponent } from './components/nav/nav-main.component'
import { NavGuestComponent } from './components/nav/nav-guest.component'

declare const App: { user: any }

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, NavMainComponent, NavGuestComponent],
  template: `
    <div id="app">
      @if (auth.isAuthenticated()) {
        <app-nav-main />
      } @else {
        <app-nav-guest />
      }
      <main class="py-6 bg-white dark:bg-gray-900">
        <router-outlet />
      </main>
    </div>
  `,
})
export class AppComponent implements OnInit {
  auth = inject(AuthService)

  ngOnInit(): void {
    this.auth.setUser(window?.App?.user ?? null)
  }
}
