// resources/js/components/common/stock-location-modal.component.ts
import { Component, signal, inject } from '@angular/core'
import { CommonModule } from '@angular/common'
import { StockLocationService } from '../../services/stock-location.service'
import { ModalComponent } from './modal.component'
import { StockLocationFormComponent } from './stock-location-form.component'

@Component({
  selector: 'app-stock-location-modal',
  standalone: true,
  imports: [CommonModule, ModalComponent, StockLocationFormComponent],
  template: `
    <div>
      <button
        type="button"
        (click)="openModal()"
        class="px-4 py-2 bg-indigo-600 text-white rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
      >
        Create New Location
      </button>

      <app-modal [isOpen]="isOpen()" title="Create New Stock Location" (close)="closeModal()">
        <app-stock-location-form (submitForm)="submitForm()" />
      </app-modal>
    </div>
  `,
})
export class StockLocationModalComponent {
  stockLocationService = inject(StockLocationService)
  isOpen = signal(false)

  openModal(): void {
    this.stockLocationService.resetStockLocation()
    this.isOpen.set(true)
  }

  closeModal(): void {
    this.isOpen.set(false)
  }

  async submitForm(): Promise<void> {
    if (await this.stockLocationService.createStockLocation()) {
      this.closeModal()
      await this.stockLocationService.loadStockLocations()
    }
  }
}

// resources/js/components/common/StockLocationModal.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { useStockLocationStore } from "../../stores/stock-location";
import Modal from "./Modal.vue";
import StockLocationForm from "./StockLocationForm.vue";

const store = useStockLocationStore();

const isOpen = ref(false);

// Reset form when modal opens
watch(isOpen, (newVal) => {
    if (newVal) {
        store.initStockLocation();
    }
});

const openModal = () => {
    isOpen.value = true;
};

const closeModal = () => {
    isOpen.value = false;
};

const submitForm = async () => {
    if (await store.createStockLocationItem()) {
        // Close modal and reload stock locations
        closeModal();
        await store.loadStockLocations();
    }
};
</script>

<template>
    <div>
        <button
            type="button"
            @click="openModal"
            class="px-4 py-2 bg-indigo-600 text-white rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
            Create New Location
        </button>

        <Modal
            :is-open="isOpen"
            title="Create New Stock Location"
            @close="closeModal"
        >
            <StockLocationForm @submit-form="submitForm" />
        </Modal>
    </div>
</template>
